@startuml
class RouteInfoImageConverter {
    + Convert(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
    + ConvertBack(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
}
IValueConverter <|-- RouteInfoImageConverter
@enduml
