@startuml
class DALDBConnectionException {
    + DALDBConnectionException()
    + DALDBConnectionException(message:string)
    + DALDBConnectionException(message:string, inner:Exception)
}
Exception <|-- DALDBConnectionException
@enduml
