@startuml
class DALRepositoryCommandException {
    + DALRepositoryCommandException()
    + DALRepositoryCommandException(message:string)
    + DALRepositoryCommandException(message:string, inner:Exception)
}
Exception <|-- DALRepositoryCommandException
@enduml
