@startuml
class DALUnitOfWorkException {
    + DALUnitOfWorkException()
    + DALUnitOfWorkException(message:string)
    + DALUnitOfWorkException(message:string, inner:Exception)
}
Exception <|-- DALUnitOfWorkException
@enduml
