@startuml
abstract class BaseViewModel {
    +  <<event>> PropertyChanged : PropertyChangedEventHandler 
    # <<virtual>> OnPropertyChanged(propertyName:string) : void
}
INotifyPropertyChanged <|-- BaseViewModel
@enduml
