@startuml
class CommonConfigException {
    + CommonConfigException()
    + CommonConfigException(message:string)
    + CommonConfigException(message:string, inner:Exception)
}
Exception <|-- CommonConfigException
@enduml
